language: node_js

node_js:
  - "12"

os:
  - windows
  - linux

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco upgrade chocolatey; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ci/install.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ci/install_linux.sh; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ci/build.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ci/build_linux.sh; fi
