language: node_js

node_js:
  - "12"

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      compiler: gcc
    - os: linux
      dist: focal
      compiler: gcc
    - os: windows

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco upgrade chocolatey; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ci/install_win.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ci/install_linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ci/install_osx.sh; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ci/build_win.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ci/build_linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ci/build_osx.sh; fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ci/after_success_win.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ci/after_success_linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ci/after_success_osx.sh; fi

deploy:
  provider: releases
  api-key: "$GITHUB_TOKEN"
  file_glob: true
  file: dist/installer/*.*
  skip_cleanup: true
  on:
    tags: true
