language: cpp

node_js:
  - "12"
  
compiler: gcc

os:
  - windows

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco upgrade chocolatey; fi
  
install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ci/install.bat; fi
  
script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ci/build.bat; fi
